apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "akscluster001-84f3"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "akscluster001-84f3"
    spec:
      containers:
        - name: "akscluster001-84f3"
          image: "calc2020.azurecr.io/akscluster001"
          ports:
          - containerPort: 3000